### ISSUE TITLE
[Kirby 3] Default value

### ISSUE THREAD

**Issue by medienbaecker** [sylvainjule/kirby-imageradio#4]
I think a `default` value is missing from the Kirby 3 version. Or am I doing something wrong?

```yaml
beverage:
  label: Beverage
  type: imageradio
  default: wine
  options: 
    beer:
      text: Beer
      image: beer.jpg
    wine:
      text: Wine
      image: wine.jpg
```
